'use client';

import { ArrowDownRight, ArrowUpRight, Check, Menu, X } from 'lucide-react';
import { useState } from 'react';
import { Button } from '@/components/ui/button';

const metrics = [['1.1M', 'Top video views'], ['22.3K', 'Total likes'], ['19.7K', 'Views in 365 days'], ['96.9%', 'Search traffic']];

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  const scrollToWork = () => document.getElementById('work')?.scrollIntoView({ behavior: 'smooth' });
  return <main>
    <nav className="site-nav"><a className="brand" href="#top">Deem Alosili<span>.</span></a><div className="nav-links"><a href="#work">Work</a><a href="#about">About</a><a href="mailto:hello@yourname.com">Contact</a></div><Button variant="ghost" size="icon" className="menu-button" aria-label="Open menu"><Menu /></Button></nav>
    <section id="top" className="hero-section"><p className="eyebrow">DEEM ALOSILI · CONTENT CREATOR &amp; STRATEGIST</p><h1>Stories that<br /><em>move people.</em></h1><div className="hero-bottom"><p>I turn everyday moments into content people stop, feel, and act on.</p><button className="round-action" onClick={scrollToWork} aria-label="View selected work"><ArrowDownRight /></button></div><div className="orb orb-one" /><div className="orb orb-two" /></section>
    <section id="work" className="work-section"><div className="section-heading"><p className="eyebrow">SELECTED WORK / 01</p><p>Scroll to explore</p></div><article className="case-card"><div className="case-image-wrap"><div className="iphone-frame"><span className="iphone-speaker" /><img src="/case-studies/newroom-profile.png" alt="Newroom Ideas TikTok account" className="case-image" /><span className="iphone-home" /></div><div className="metric-bubble bubble-views"><strong>1.1M</strong><span>views</span></div><div className="metric-bubble bubble-likes"><strong>22.3K</strong><span>likes</span></div><div className="metric-bubble bubble-shares"><strong>29</strong><span>shares</span></div><span className="image-label">TIKTOK / 2025–26</span></div><div className="case-summary"><p className="eyebrow">CONTENT STRATEGY · STORYTELLING</p><h2>Newroom<br /><em>Ideas</em></h2><p>I built a story-led content direction that turned bedroom challenges into helpful, searchable, solution-focused videos.</p><Button onClick={() => setIsOpen(true)} className="case-button">Explore case study <ArrowUpRight data-icon="inline-end" /></Button></div></article></section>
    <section id="about" className="about-section"><p className="eyebrow">THE WAY I WORK</p><h2>Story first.<br />Strategy always.</h2><p className="about-copy">From a single idea to a full content direction, I make marketing feel human—because the best content earns attention before it asks for it.</p><div className="services-list">{['Content strategy', 'Storytelling', 'Video concepts', 'Copywriting'].map((service, index) => <p key={service}><span>0{index + 1}</span>{service}</p>)}</div></section>
    <footer><p>Available for creative collaborations</p><a href="mailto:hello@yourname.com">Let’s work together <ArrowUpRight /></a></footer>
    {isOpen && <div className="modal-backdrop" role="dialog" aria-modal="true" aria-labelledby="case-title"><div className="case-modal"><Button variant="ghost" size="icon" className="close-button" onClick={() => setIsOpen(false)} aria-label="Close case study"><X /></Button><div className="modal-title"><p className="eyebrow">CASE STUDY / 01</p><h2 id="case-title">Newroom Ideas</h2><p>@newroom_ideas · Bedroom solutions &amp; ideas</p></div><div className="modal-grid"><section className="analysis-card" aria-label="TikTok performance analysis"><div className="analysis-topline"><span>PERFORMANCE SNAPSHOT</span><span>365 DAYS</span></div><div className="analysis-primary"><p>Post views</p><strong>19.7K</strong><span>Sep 8, 2025 — Sep 7, 2026</span></div><div className="analysis-divider" /><div className="analysis-discovery"><p>Search-led discovery</p><strong>96.9%</strong><span>of traffic came from TikTok Search</span><div className="search-bar" aria-label="96.9 percent of traffic from search"><i /></div></div><div className="analysis-breakdown"><div><strong>369</strong><span>Profile views</span></div><div><strong>152</strong><span>Likes</span></div><div><strong>29</strong><span>Shares</span></div></div><p className="analysis-source">Source: TikTok Analytics</p></section><div className="modal-copy"><div><p className="eyebrow">THE APPROACH</p><p>I translated storytelling into a marketing direction: every video began with a familiar room problem, then made the solution simple, useful, and easy to share.</p></div><div><p className="eyebrow">CONTENT FOCUS</p><p>Before &amp; after moments · décor ideas · product-led tips</p></div></div></div><div className="metrics-grid">{metrics.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span><Check /></div>)}</div><button className="modal-close-text" onClick={() => setIsOpen(false)}>Close case study</button></div></div>}
  </main>;
}
